apiVersion: v1
kind: Service
metadata:
    name: influxdb-nodeport
spec:
    type: NodePort
    selector:
        component: influxdb
    ports:
    -   port: 8086
        targetPort: 8086
        nodePort: 8086
        protocol: TCP