apiVersion: v1
kind: Service
metadata:
    name: telegraf-nodeport
spec:
    type: NodePort
    selector:
        component: telegraf
    ports:
    -   port: 4999
        targetPort: 4999
        nodePort: 4999
        protocol: TCP