apiVersion: v1
kind: Service
metadata:
    name: nginx-nodeport
spec:
    type: NodePort
    selector:
        component: nginx
    ports:
    -   port: 22
        targetPort: 22
        nodePort: 22
        protocol: TCP
    -   port: 443
        targetPort: 443
        nodePort: 443
        protocol: TCP