apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-nodeport
spec:
    type: NodePort
    selector:
        component: phpmyadmin
    ports:
    -   port: 5000
        targetPort: 5000
        nodePort: 5000
        protocol: TCP