apiVersion: v1
kind: Service
metadata:
    name: wordpress-nodeport
spec:
    type: NodePort
    selector:
        component: wordpress
    ports:
    -   port: 5050
        targetPort: 5050
        nodePort: 5050
        protocol: TCP