apiVersion: v1
kind: Service
metadata:
    name: grafana-nodeport
spec:
    type: NodePort
    selector:
        component: grafana
    ports:
    -   port: 3000
        targetPort: 3000
        nodePort: 3000
        protocol: TCP